server:
   port: 8222
   servlet:
     context-path: /wechatoa
#http://localhost:8085/signin/hello
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechatoa_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
     #  password: 123456
    sql-script-encoding: utf-8
